"""Asynchronous SQLAlchemy infrastructure for AegisGraph AI.

The API dependency yields transaction-safe sessions, while workers and scripts
can use ``session_scope`` for explicit unit-of-work semantics. Engine creation
is lazy so importing models never opens a database connection.
"""

from __future__ import annotations

from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4

from sqlalchemy import DateTime, MetaData, Uuid, text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from app.core.config import Settings, get_settings


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base with deterministic constraint names for Alembic."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """Provide a UUID primary key generated by the application."""

    id: Mapped[UUID] = mapped_column(Uuid(as_uuid=True), primary_key=True, default=uuid4)


class TimestampMixin:
    """Provide timezone-aware creation and modification timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )


_engine: AsyncEngine | None = None
_session_factory: async_sessionmaker[AsyncSession] | None = None


def _engine_options(settings: Settings) -> dict[str, Any]:
    """Build bounded pool and PostgreSQL statement-timeout options."""

    options: dict[str, Any] = {
        "echo": settings.database_echo,
        "pool_pre_ping": True,
        "pool_size": settings.database_pool_size,
        "max_overflow": settings.database_max_overflow,
        "pool_timeout": settings.database_pool_timeout_seconds,
        "pool_recycle": settings.database_pool_recycle_seconds,
    }
    database_url = settings.database_url.get_secret_value()
    if database_url.startswith("postgresql+asyncpg://"):
        options["connect_args"] = {
            "server_settings": {
                "application_name": settings.service_instance_id,
                "statement_timeout": str(settings.database_statement_timeout_ms),
                "timezone": "UTC",
            }
        }
    return options


def get_engine(settings: Settings | None = None) -> AsyncEngine:
    """Return the process-wide async engine, creating it on first use."""

    global _engine
    if _engine is None:
        config = settings or get_settings()
        _engine = create_async_engine(
            config.database_url.get_secret_value(),
            **_engine_options(config),
        )
    return _engine


def get_session_factory(settings: Settings | None = None) -> async_sessionmaker[AsyncSession]:
    """Return a reusable session factory with safe expiration behaviour."""

    global _session_factory
    if _session_factory is None:
        _session_factory = async_sessionmaker(
            bind=get_engine(settings),
            class_=AsyncSession,
            autoflush=False,
            expire_on_commit=False,
        )
    return _session_factory


async def get_db_session() -> AsyncGenerator[AsyncSession]:
    """FastAPI dependency that rolls back failures and closes every session.

    Route handlers explicitly call ``commit`` after successful state changes.
    This avoids committing partial work if response serialization later fails.
    """

    async with get_session_factory()() as session:
        try:
            yield session
        except BaseException:
            await session.rollback()
            raise


@asynccontextmanager
async def session_scope(
    settings: Settings | None = None,
) -> AsyncGenerator[AsyncSession]:
    """Provide an atomic unit of work for consumers, jobs, and scripts."""

    async with get_session_factory(settings)() as session:
        try:
            yield session
            await session.commit()
        except BaseException:
            await session.rollback()
            raise


async def database_healthcheck(settings: Settings | None = None) -> bool:
    """Verify connectivity using a minimal read-only statement."""

    try:
        async with get_session_factory(settings)() as session:
            await session.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


async def dispose_database() -> None:
    """Close pooled connections during application shutdown or isolated tests."""

    global _engine, _session_factory
    if _engine is not None:
        await _engine.dispose()
    _engine = None
    _session_factory = None
